---
abstract: "US Holiday's as DateTime::Set objects"
author:
  - 'Alan Young <harleypig@gmail.com>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Path::Class: 0
  Scalar::Util: 0
  Test::More: 0.94
  Test::Perl::Critic::Progressive: 0
  Try::Tiny: 0
  perl: 5.004
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTime-Event-Holiday-US
no_index:
  directory:
    - t
    - xt
provides:
  DateTime::Event::Holiday::US:
    file: lib/DateTime/Event/Holiday/US.pm
    version: 0.02
requires:
  Carp: 0
  DateTime::Format::ICal: 0
  DateTime::Set: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/harleypig/datetime-event-holiday-us/issues
  repository: git://github.com/harleypig/datetime-event-holiday-us.git
version: 0.02
